### PR TITLE
chore: upgrade fast-json-stringify to ^5.7.0

### PR DESCRIPTION
**Pull request by trim21**
1.21.0 is released 3 years ago, and now it have builtin type support.

Also, `string-similarity` is deprecated, so it also cause warning in npm

### CODE REVIEW

**Comment by trim21** [comment]
> Thanks for the PR. Looks like the type checks are failing.

Yes, it's still a WIP pr

**Comment by boopathi** [comment]
There is a previous pr (https://github.com/zalando-incubator/graphql-jit/pull/195) that updates fast-json-stringify and fixes the types. Maybe we can close this and update the version in that PR to 5.x and merge that instead.

**Comment by trim21** [comment]
> There is a previous pr (#195) that updates fast-json-stringify and fixes the types. Maybe we can close this and update the version in that PR to 5.x and merge that instead.

Thanks， look like I can cherry-pick that PR

**Comment by boopathi** [comment]
yeah. Or I can also change the base branch of this PR to that branch `update-faster-json-stringify` instead of main.

**Comment by trim21** [comment]
thanks  I'll just use local git

**Comment by trim21** [comment]
I encounter a lint problem, lint failed in a test files that I didn't change.

**Comment by trim21** [comment]
@boopathi I think this PR is ready now

**Comment by oporkka** [comment]
:+1:

**Comment by boopathi** [comment]
👍

**Pull request merged**
