### PR TITLE
Add GH action for building

### PR DESCRIPTION
**Pull request by ruiaraujo**
Preparation to move away from travis.

### CODE REVIEW

**Comment by ruiaraujo** [comment]
:+1:

**Comment by ruiaraujo** [comment]
Screenshot from 2021-01-27 00-53-25
Proving my point. :smile:

**Comment by boopathi** [comment]
👍

**Comment by boopathi** [comment]
let's make travis not required and merge this. The auto-publishing alone is pending.

**Comment by mcollina** [comment]
I would recommend to drop Travis completely :/. It's unreliable today.

**Comment by ruiaraujo** [comment]
@mcollina we are in the process. :)

**Pull request merged**
