### PR TITLE
make compiled code generation logic more readable

### PR DESCRIPTION
**Pull request by vigneshshanmugam**
+ Attempt to make the code generation logic a bit more readable. 
+ Hopefully it helps the contributors to understand the logic better. 

It does not affect the benchmarks in any way. 
```
npx ts-node -T ./src/__benchmarks__/schema-many-resolvers.benchmark.ts
graphql-js x 16,583 ops/sec ±1.68% (81 runs sampled)
graphql-jit x 56,027 ops/sec ±1.66% (78 runs sampled)
Fastest is graphql-jit

npx ts-node  -T ./src/__benchmarks__/schema.benchmark.ts
graphql-js x 15,568 ops/sec ±2.22% (78 runs sampled)
graphql-jit x 132,293 ops/sec ±1.58% (78 runs sampled)
Fastest is graphql-jit
```

### CODE REVIEW

**Comment by ruiaraujo** [comment]
@vigneshshanmugam why is this draft? since the test are passing I would be fine with merging as is?

**Comment by vigneshshanmugam** [comment]
@ruiaraujo Thought of adding it for the `execution.ts`, but it's taking some time. Let me do another PR then.

**Comment by ruiaraujo** [comment]
👍

**Comment by boopathi** [comment]
👍

**Pull request merged**
