### PR TITLE
Fix typos in comments

### PR DESCRIPTION
**Pull request by trkohler**
this PR is needed so I can merge the other my PR easily and it would have github actions run against it without additional approval.

### CODE REVIEW

**Review by boopathi — APPROVED** [review]

**Comment by addityasingh** [comment]
👍

**Review by addityasingh — APPROVED** [review]

**Comment by oporkka** [comment]
:+1:

**Comment by trkohler** [comment]
👍

**Comment by trkohler** [comment]
seems like one more zappr is needed

**Comment by boopathi** [comment]
👍

**Pull request merged**
