### PR TITLE
Release 0.5.0

### PR DESCRIPTION
**Pull request by ruiaraujo**
Skip/include is finally here!

### CODE REVIEW

**Comment by ruiaraujo** [comment]
:+1:

**Comment by boopathi** [comment]
Travis is taking too much time. Let's add publishing to GH Actions.

**Comment by ruiaraujo** [comment]
yup, I agree

**Comment by ruiaraujo** [comment]
@boopathi I would still approve it and once the build passes, we can merge it.

**Comment by boopathi** [comment]
👍

**Pull request merged**
