### PR TITLE
Upgrade GraphQL to v15

### PR DESCRIPTION
**Pull request by frikille**
Fixed the two failing tests caused by text change and order of object properties.

### CODE REVIEW

**Comment by ruiaraujo** [comment]
For some reason yarn is complaining. :confused: 

Can you run it and commit what is wrong?

**Comment by addityasingh** [comment]
@frikille You need to update the yarn.lock file by running yarn again. The build fails with below error

>yarn --frozen-lockfile
yarn install v1.15.2
[1/4] Resolving packages...
error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by frikille** [comment]
@addityasingh Updated `yarn.lock` and it seems CI is passing now

**Comment by addityasingh** [comment]
👍

**Comment by ruiaraujo** [comment]
:+1:

**Pull request merged**
