### PR TITLE
compact generated code to calculate size

### PR DESCRIPTION
**Pull request by boopathi**
this is a patch request to #98 to compute the size of the function body after compact print - remove unnecessary whitespace.

### CODE REVIEW

**Comment by ruiaraujo** [comment]
I kinda disagree because what we produce is what gets stored in memory. This captures a different number that is not relevant. Whitespace does matter since it takes space currently.

**Comment by boopathi** [comment]
Once you use the string inside `new Function`, the whitespace does not matter. The string gets GCed, isn't it? We do not save the generated code in memory. Only when `debug` is true, we even store that string in the compiled object.

**Comment by ruiaraujo** [comment]
It stays in memory. You can do function.toString() and it will have the original. If it was GCed, I would not care about code size.

**Comment by boopathi** [comment]
🤦‍♂️. okay. Then we are better off optimizing the generate code.

**Pull request closed without merging**
