### PR TITLE
Remove custom json serializer.

### PR DESCRIPTION
**Pull request by ruiaraujo**
I benchmarked this feature and it either had no impact or negative on a end to end benchmark.

### CODE REVIEW

**Comment by ruiaraujo** [comment]
:+1:

**Comment by ruiaraujo** [comment]
This is the benchmark I am using https://github.com/ruiaraujo/gbench/tree/json.

The results are mixed. I will try adding a more complex schema to get to a final decision.

**Comment by mcollina** [comment]
Which version of Node.js are you using? There are differences between Node 8, Node 10 and Node 12. In Node < 12, you’ll need http://npm.im/flatstr to avoid certain issues with internal string representation.

**Comment by ruiaraujo** [comment]
I will try running with Node 12 and report back.

**Pull request closed without merging**
